# deployment/prometheus/rules/alert_rules.yml
groups:
  - name: bike-alerts
    rules:
      - alert: BikeApiDown
        expr: up{job="bike_api"} == 0     # The PromQL condition that triggers the alert
        for: 1m                           # The alert triggers if the condition is true for 1 continuous minute
        labels:
          severity: critical              # Label for the severity of the alert (useful for filtering and prioritizing)
        annotations:
          summary: "The bike API is unreachable."
          description: "The job 'bike_api' has been DOWN (unreachable) for more than 1 minute. Please check the `news-classifier` container."
    